import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  botContainer: {
    backgroundColor: '#3a3967',
    height: '60%',
    shadowOffset: {width: 10, height: 10},
    shadowColor: 'black',
    shadowOpacity: 1.0,
  },
  topContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    height: '50%',
  },
  textBox: {
    color: '#fff',
    fontSize: 16,
    borderBottomColor: '#fff',
    borderBottomWidth: 1,
    marginTop: 10,
    marginHorizontal: 40,
    height: 40,
    padding: 10,
  },
  loginText: {
    color: '#fff',
    fontSize: 16,
    alignItems: 'flex-start',
    marginLeft: 40,
    marginTop: 20,
  },
  entrarButton: {
    backgroundColor: '#3a3967',
    padding: 10,
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: 15,
    marginTop: 45,
    marginHorizontal: 40,
  },
  entrarButtonText: {
    color: '#fff',
    textAlign: 'center',
    margin: 10,
  },
  rastreador: {
    color: '#207dd2',
    fontSize: 31,
    marginTop: 0.1,
    textAlign: 'center',
    alignSelf: 'center',
  },
  mcgt: {
    color: '#f9f9f9',
    fontSize: 30,
    marginTop: 20,
    justifyContent: 'center',
    textAlign: 'center',
  },
  homeBemvindo: {
    fontSize: 20,
    color: '#3a3967',
    textAlign: 'center',
    bottom: 43,
    fontWeight: 'bold',
    right: 30,
  },
  blueCircle: {
    borderRadius: 50,
    backgroundColor: 'white',
    height: 55,
    width: 55,
    borderWidth: 3,
    borderColor: '#3a3967',
    marginLeft: 35,
    marginTop: 35,
  },
  blueCircle2: {
    borderRadius: 50,
    backgroundColor: '#3a3967',
    height: 44,
    width: 44,
    top: 2,
    left: 2,
  },
  grayBox: {
    backgroundColor: '#dbdbdb',
    width: '85%',
    height: 200,
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 40,
  },
  grayBoxDetalhes: {
    backgroundColor: '#dbdbdb',
    width: '80%',
    height: 165,
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 10,
    marginBottom: 10,
  },
  homeText: {
    fontWeight: 'bold',
    color: '#3a3967',
    textAlign: 'left',
    fontSize: 22,
    marginLeft: 40,
    marginBottom: 5,
  },
  grayBoxSmallText: {
    fontSize: 16,
    textAlign: 'center',
    top: 30,
    opacity: 0.5,
  },
  grayBoxBigText: {
    fontSize: 96,
    color: '#4488ee',
    textAlign: 'center',
    top: 20,
  },
  grayBoxCadastro: {
    backgroundColor: '#dbdbdb',
    width: '85%',
    height: 80,
    alignSelf: 'center',
    borderRadius: 10,
    marginBottom: 20,
  },
  grayBoxTextCadastro: {
    fontSize: 16,
    color: '#3a3967',
    textAlign: 'left',
    marginLeft: 20,
    marginTop: 30,
  },
  verButton: {
    borderRadius: 10,
    backgroundColor: '#dbdbdb',
    height: 50,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    borderColor: '#3a3967',
    borderWidth: 3,
    bottom: 37,
    marginRight: 20,
  },
  verText: {
    fontSize: 18,
    color: '#3a3967',
  },
  truckText: {
    color: '#3a3967',
    fontSize: 24,
    fontWeight: 'bold',
    marginLeft: 40,
  },
  ewayTruck: {
    resizeMode: 'contain',
    width: 350,
    bottom: 0,
  },
  yellowTruck: {
    resizeMode: 'contain',
    width: '80%',
    alignSelf: 'center',
    bottom: 35,
  },
  dadosText: {
    color: '#3a3967',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 40,
    marginBottom: 0.4,
  },
  dadosInsideText: {
    color: '#3a3967',
    fontSize: 16,
  },
  editarDados: {
    borderRadius: 10,
    height: 45,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    borderColor: '#3a3967',
    borderWidth: 3,
    marginBottom: 5,
    marginTop: 10,
  },
  rastrearCaminhao: {
    backgroundColor: '#3a3967',
    borderRadius: 10,
    height: 45,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    width: '80%',
    marginTop: 5,
  },
  textRastrear: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  textEditar: {
    color: '#3a3967',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  primeiraRoda: {
    borderRadius: 200,
    backgroundColor: '#dfdfdf',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 300,
    width: 300,
  },
  segundaRoda: {
    backgroundColor: '#ececec',
    borderRadius: 200,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 250,
    width: 250,
  },
  terceiraRoda: {
    borderRadius: 200,
    backgroundColor: 'white',
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: 200,
    width: 200,
  },
  yellowTruckRastrear: {
    resizeMode: 'contain',
    width: '80%',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  textLocalizacao: {
    color: '#3a3967',
    fontSize: 18,
    textAlign: 'center',
    top: 20,
  },
  bigTextLocalizacao: {
    fontSize: 96,
    color: '#4488ee',
    textAlign: 'center',
  },
  map: {
    width: '100%',
    height: '100%',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
  },
  emergencyCallBox: {
    backgroundColor: '#3a3967',
    width: '92%',
    height: 120,
    alignSelf: 'center',
    borderRadius: 10,
    position: 'absolute',
    justifyContent: 'flex-end',
    bottom: 15,
  },
  btn190: {
    backgroundColor: '#ff3636',
    width: 80,
    height: 50,
    borderRadius: 10,
    position: 'absolute',
    alignSelf: 'center',
    bottom: 35,
    right: 30,
  },
  btnText190: {
    color: '#fff',
    textAlign: 'center',
    justifyContent: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    top: 10,
  },
  emergencyCall: {
    backgroundColor: '#3a3967',
    width: 230,
    height: 50,
    alignSelf: 'center',
    borderRadius: 10,
    position: 'absolute',
    justifyContent: 'center',
    borderColor: '#fff',
    borderWidth: 3,
    bottom: 35,
    left: 25,
  },
  textAcionar: {
    color: '#fff',
    textAlign: 'center',
    justifyContent: 'center',
  },
  grayBoxSmallTextDados: {
    fontSize: 12,
    textAlign: 'right',
    top: 30,
    opacity: 0.5,
    marginRight: 20,
  },
  grayBoxBigTextDados: {
    fontSize: 96,
    color: '#4488ee',
    textAlign: 'right',
    top: 20,
    marginRight: 5,
  },
  grayBoxDados: {
    backgroundColor: '#dbdbdb',
    width: '85%',
    height: 200,
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 15,
    marginBottom: 40,
  },
  coluna1: {
    backgroundColor: '#1c85e5',
    width: 25,
    height: 125,
    borderRadius: 10,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    bottom: 95,
    marginLeft: 6,
    left: 10,
  },
  coluna2: {
    backgroundColor: '#1c85e5',
    width: 25,
    height: 100,
    borderRadius: 10,
    alignSelf: 'flex-start',
    bottom: 195,
    marginLeft: 6,
    left: 40,
  },
  coluna3: {
    backgroundColor: '#1c85e5',
    width: 25,
    height: 80,
    borderRadius: 10,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    bottom: 275,
    marginLeft: 6,
    left: 70,
  },
  coluna4: {
    backgroundColor: '#1c85e5',
    width: 25,
    height: 100,
    borderRadius: 10,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    bottom: 375,
    marginLeft: 6,
    left: 100,
  },
  coluna5: {
    backgroundColor: '#1c85e5',
    width: 25,
    height: 60,
    borderRadius: 10,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    bottom: 435,
    marginLeft: 6,
    left: 130,
  },
});
